version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app_contabilize
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      PORT: ${PORT:-3000}
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:password@postgres:5432/contabilize}
    command: >
      sh -c "npx prisma migrate deploy && node dist/main.js"

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contabilize
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  db-seed:
    image: postgres
    restart: "no"
    depends_on:
      - postgres
    volumes:
      - ./backup.dump:/tmp/backup.dump:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contabilize
    entrypoint: ["bash","-c"]
    command: >
      "echo 'Aguardando Postgres...'; \
      until pg_isready -h postgres -U $POSTGRES_USER -d $POSTGRES_DB; do sleep 1; done; \
      export PGPASSWORD=$POSTGRES_PASSWORD; \
      COUNT=$(psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -tAc \"SELECT COUNT(*) FROM \"public\".\"Account\"\"); \
      if [ \"$COUNT\" = \"0\" ]; then \
        echo 'Banco vazio, restaurando dump inicial...'; \
        (pg_restore -h postgres -U $POSTGRES_USER -d $POSTGRES_DB --clean --if-exists --no-owner --no-privileges /tmp/backup.dump || psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -f /tmp/backup.dump) && echo 'Restauração concluída.'; \
      else \
        echo 'Banco já possui dados (Account count='\"$COUNT\"'), ignorando restauração.'; \
      fi"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      # Mapeia o arquivo que criamos na pasta local para dentro do container
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000" # Porta 3001 no seu PC acessa a 3000 do Grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge